thread_seeking_tid:  thread_seeking_tid.o 
	        gcc -pthread -o thread_seeking_tid thread_seeking_tid.o 

thread_seeking_tid.o:        thread_seeking_tid.c
	        gcc -c thread_seeking_tid.c

clean:
	    	rm *.o
		rm thread_seeking_tid
