tef6638_to_array:  tef6638_to_array.o
	        gcc -o tef6638_to_array tef6638_to_array.o

tef6638_to_array.o:        tef6638_to_array.c
	        gcc -c tef6638_to_array.c

clean:
	    	rm *.o
		rm tef6638_to_array
