thread_create:  thread_create.o 
	        gcc -pthread -o thread_create thread_create.o 

thread_create.o:        thread_create.c
	        gcc -c thread_create.c

clean:
	    	rm *.o
		rm thread_create
